[build-system]
requires = ["setuptools", "setuptools-scm"]

[tool.isort]
profile = "black"

[[tool.mypy.overrides]]
# Packages/modules for which no type hints are available.
module = [
  "asyncssh",
  "matplotlib.*",
  "numpy",
  "pandas.*",
  "pint",
  "pyam",
  "pytest",
  "setuptools",
  "xarray",
  # Indirectly via ixmp; this should be a subset of the list in ixmp's setup.cfg
  "dask",
  "jpype",
  "nbclient",
  "nbformat",
  "memory_profiler",
  "sparse",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
# Disable faulthandler plugin on Windows to prevent spurious console noise
addopts = """
  --cov=message_ix --cov-report=
  -m "not nightly and not rmessageix"
  -p no:faulthandler"""
markers = [
  "nightly: Slow-running nightly tests of particular scenarios.",
  "rmessageix: test of the message_ix R interface.",
]