# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# The action runs when:
# - A new release is published
# - A new commit is pushed to main
# For customizing the triggers, visit https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  release:
    types: [published]
  push:
    branches: [main]
  workflow_dispatch:

name: Update CITATION.cff

jobs:
  update-citation-cff:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install required python packages
        run: pip install pyyaml os
      #------------------------------------------------------
      #       Set environment variables and update file
      #------------------------------------------------------
      - name: Update citation file
        run: |
          import os
          import yaml

          github_event_name = os.environ.get("GITHUB_EVENT_NAME")
          if github_event_name == "release":
              latest_version = os.environ.get("GITHUB_REF_NAME")
          elif github_event_name == "push":
              latest_commit = os.environ.get("GITHUB_SHA")

          with open("CITATION.cff", "r+"") as f:
              data = yaml.load(f, Loader=yaml.loader.BaseLoader)
              if github_event_name == "release":
                  data["version"] = latest_version[1:]
              elif github_event_name == "push":
                  data["commit"] = latest_commit
              yaml.dump(data, f, sort_keys=False)
        shell: python
      #------------------------------------------------------
      #       Commit updated file to Github
      #------------------------------------------------------
      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add CITATION.cff
          git commit -m 'Update CITATION.cff' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
      - name: State result
        run: echo "CITATION.cff has been updated correctly"